sudo: false

os:
  - osx
  - linux

env:
  - HasVs=true CMT_TESTING=1


before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish
  - scripts/prepare_test.sh

script:
  - node --version
  - node ./node_modules/vscode/bin/test